#pragma once
#define ABLAZE_MOUSE_BUTTON_1         0
#define ABLAZE_MOUSE_BUTTON_2         1
#define ABLAZE_MOUSE_BUTTON_3         2
#define ABLAZE_MOUSE_BUTTON_4         3
#define ABLAZE_MOUSE_BUTTON_5         4
#define ABLAZE_MOUSE_BUTTON_6         5
#define ABLAZE_MOUSE_BUTTON_7         6
#define ABLAZE_MOUSE_BUTTON_8         7
#define ABLAZE_MOUSE_BUTTON_LAST      HZ_MOUSE_BUTTON_8
#define ABLAZE_MOUSE_BUTTON_LEFT      HZ_MOUSE_BUTTON_1
#define ABLAZE_MOUSE_BUTTON_RIGHT     HZ_MOUSE_BUTTON_2
#define ABLAZE_MOUSE_BUTTON_MIDDLE    HZ_MOUSE_BUTTON_3